version: "3.7"

services:
  plex:
    container_name: plex
    image: cr.hotio.dev/hotio/plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - PLEX_CLAIM
      - ADVERTISE_IP
      - ALLOWED_NETWORKS
      - PLEX_PASS=no
    volumes:
      - /<host_folder_config>:/config
      - /<host_folder_transcode>:/transcode
