version: "3.7"

services:
  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /<host_folder_config>:/config
